// 브릿지: Phase 7에서 삭제
export { HEALTH_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/health-analysis'
export { buildHealthAnalysisPrompt } from '@/shared/lib/health-prompt'
export { SUPPLEMENT_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/supplement-rec'
export { SIDE_EFFECT_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/side-effect'
export { SAJU_SYSTEM_PROMPT } from '@/features/saju/lib/prompts/saju-analysis'
export { RISK_ASSESSMENT_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/risk-assessment'
export { EXERCISE_RX_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/exercise-rx'
export { NUTRITION_ANALYSIS_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/nutrition-analysis'
export { CORRELATION_SYSTEM_PROMPT } from '@/features/insight/lib/prompts/correlation'
